let Guests = ['Umair','Uzair','Ahmed','Shaheer','Samad'];
console.log(Guests[2] + " is not coming in dinner");
NewGuest = 'Ghulam';
Guests.splice(2,1,NewGuest);
console.log(Guests);
console.log("New List");
console.log("We have found a bigger table for dinner ");
console.log(Guests.unshift('Hamza'));
console.log(Guests.splice(4,0,'Ather'));
console.log(Guests.push('Rafay'));
console.log(Guests);
let newmessage = " Hurray!! Dinner have arranged on big table";
console.log(Guests[0] + newmessage);
console.log(Guests[1] + newmessage);
console.log(Guests[2] + newmessage);
console.log(Guests[3] + newmessage);
console.log(Guests[4] + newmessage);
console.log(Guests[5] + newmessage);
console.log(Guests[6] + newmessage);
console.log(Guests[7] + newmessage);