let Guests = ['Umair','Uzair','Ahmed','Shaheer','Samad'];
console.log(Guests[2] + " is not coming in dinner");
NewGuest = 'Ghulam';
Guests.splice(2,1,NewGuest);
console.log(Guests);
console.log("New List");
console.log(Guests[0] + invitation);
console.log(Guests[1] + invitation);
console.log(Guests[2] + invitation);
console.log(Guests[3] + invitation);
console.log(Guests[4] + invitation);
console.log(" :( I have only space for two persons now...")
console.log(Guests.pop()+ " I'm sorry I can't invite you on dinner :(");
console.log(Guests);
console.log(Guests.pop()+ " I'm sorry I can't invite you on dinner :(");
console.log(Guests);
console.log(Guests.pop()+ " I'm sorry I can't invite you on dinner :(");
console.log(Guests);
console.log(Guests.pop()+ " I'm sorry I can't invite you on dinner :(");
console.log(Guests);
console.log(Guests.pop()+ " I'm sorry I can't invite you on dinner :(");
console.log(Guests);
console.log(Guests.pop()+ " I'm sorry I can't invite you on dinner :(");
console.log(Guests);
let msg = " You are still invited ;)";
console.log(Guests[0] + msg);
console.log(Guests[1] + msg);
console.log(Guests.pop());
console.log(Guests.pop());
console.log(Guests);
